Catch KeyError when getting breakpoints
cyrus-and/gdb-dashboard pull request #250
Opened 2021-08-19 13:59 UTC by jannewulf

I would have talked to you before making the PR, but it's a really small bug fix.

I had the situation where getting the breakpoints failed because one of the `gdb_breakpoint.number` was `-1`. This resulted in error messages in the `Assembly` and the `Breakpoints` section.

The bug fix just ignores these invalid breakpoints. I still saw all my created breakpoints in my situation. So, there were indeed some invalid breakpoints.

2021-08-19 14:19 UTC, cyrus-and commented
> I had the situation where getting the breakpoints failed because one of the `gdb_breakpoint.number` was `-1`.

Do you know why is this the case / how to reproduce it?

2021-08-19 16:41 UTC, jannewulf commented
I have used a modified gdb version for the NEC SX-Aurora TSUBASA device. With this gdb version, I had this problem with every executable I tried. Could be a bug in their modifications. But I thought it could also be helpful for the standard gdb since -1 seems to be an invalid id.

2021-08-20 06:50 UTC, cyrus-and commented
I see, can you show me the output of `info breakpoints` in such cases?

2021-08-20 06:57 UTC, cyrus-and commented
OK they could be legitimate [internal](https://sourceware.org/gdb/current/onlinedocs/gdb/Set-Breaks.html#index-negative-breakpoint-numbers) breakpoints:

> GDB itself sometimes sets breakpoints in your program for special purposes, such as proper handling of longjmp (in C programs). These internal breakpoints are assigned negative numbers, starting with -1; ‘info breakpoints’ does not display them. You can see these breakpoints with the GDB maintenance command ‘maint info breakpoints’ (see maint info breakpoints).

Can you confirm with `maint info breakpoints`?

2021-08-20 08:40 UTC, jannewulf commented
Yes, there are indeed internal breakpoints that cause this.
```
>>> info breakpoints
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000060000000e280 <Benchmark::operator()()+288>
	breakpoint already hit 1 time
>>> maint info breakpoints
Num     Type                  Disp Enb Address            What
-1      breakpoint            keep y   <PENDING>          __pdbx_switch_to_debugger
1       breakpoint            keep y   0x000060000000e280 <Benchmark::operator()()+288> inf 1
	breakpoint already hit 1 time
-2      shlib events          keep y   0x0000600c00044090 <__GI__dl_debug_state> inf 1
-3      std::terminate master keep n   0x0000600c00b536b0 <std::terminate()> inf 1
```

I am happy to make further changes to handle this, but let's first discuss how. I see two possibilities to handle this:
1. Show also internal breakpoints. Probably best to have a setting for this.
2. Keep showing just user breakpoints but handle that by checking the breakpoint number. 

I would prefer 2 because it is very rare that users would want to see internal breakpoints. And even then, they can still run `maint info breakpoints`. What do you think?

2021-08-20 09:36 UTC, cyrus-and commented
Nice, yeah let's just skip those having a negative number, better leave the `KeyError` unhandled to (hopefully not) *catch* other unknown behaviours in the future, thanks.

2021-08-20 10:00 UTC, cyrus-and requested changes

2021-08-20 10:00 UTC, cyrus-and commented on .gdbinit
> +          continue
Please use 4 spaces indentation.

2021-08-20 10:13 UTC, cyrus-and approved these changes

2021-08-20 10:14 UTC, merged

2021-08-20 10:15 UTC, cyrus-and commented
Perfect, thank you so much!